// // import { prisma } from "@/prisma";
// import { prisma } from "@/lib/prisma";
// import { notFound } from "next/navigation";
// import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
// import { Badge } from "@/components/ui/badge";
// import { MapPin, Clock, Banknote } from "lucide-react";

// export default async function TripPage({ params }: { params: { id: string } }) {
//   // 1. Fetch the specific trip from Supabase
//   const trip = await prisma.trip.findUnique({
//     where: { id: params.id },
//   });

//   // If the ID is wrong, show a 404 page
//   if (!trip) return notFound();

//   // Parse the AI JSON (we typecast it to `any` here for simplicity)
//   const itineraryData: any = trip.itinerary;

//   return (
//     <main className="min-h-screen bg-[#FDFBF7] py-12 px-6">
//       <div className="max-w-3xl mx-auto">
        
//         {/* Header Section */}
//         <div className="text-center mb-12">
//           <Badge className="bg-amber-100 text-amber-800 hover:bg-amber-100 mb-4 px-4 py-1 text-sm rounded-full">
//             {trip.duration} Days • {trip.members} Travelers • {trip.budget}
//           </Badge>
//           <h1 className="text-5xl font-serif text-slate-900 mb-4">
//             Your {trip.destination} Itinerary
//           </h1>
//           <p className="text-slate-500 text-lg">{itineraryData.trip_name || "A beautifully curated journey."}</p>
//         </div>

//         {/* The Itinerary Timeline */}
//         <div className="space-y-8">
//           {itineraryData.itinerary?.map((day: any, index: number) => (
//             <Card key={index} className="border-none shadow-md overflow-hidden rounded-2xl">
//               <CardHeader className="bg-slate-900 text-white py-4">
//                 <CardTitle className="text-xl font-medium tracking-wide">
//                   Day {day.day}: {day.theme}
//                 </CardTitle>
//               </CardHeader>
              
//               <CardContent className="p-6 space-y-6 bg-white">
//                 {day.activities?.map((activity: any, actIndex: number) => (
//                   <div key={actIndex} className="flex gap-4 border-b border-slate-100 pb-4 last:border-0 last:pb-0">
//                     <div className="text-slate-400 mt-1"><Clock size={20} /></div>
//                     <div>
//                       <p className="font-semibold text-slate-800 text-lg">{activity.time}</p>
//                       <p className="text-slate-600 mt-1">{activity.description}</p>
                      
//                       <div className="flex gap-4 mt-3 text-sm text-slate-500 font-medium">
//                         <span className="flex items-center gap-1"><MapPin size={16}/> {activity.location}</span>
//                         <span className="flex items-center gap-1 text-emerald-600"><Banknote size={16}/> ₹{activity.est_cost_in_inr}</span>
//                       </div>
//                     </div>
//                   </div>
//                 ))}
//               </CardContent>
//             </Card>
//           ))}
//         </div>

//       </div>
//     </main>
//   );
// }


// app/trip/[id]/page.tsx
import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { MapPin, Clock, IndianRupee } from "lucide-react";

// The 'params' object automatically grabs the ID from the URL (e.g., /trip/[id])
// In Next.js 16, params is a Promise and needs to be awaited
export default async function TripResultsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  
  // 1. Ask Prisma to find the exact trip in Supabase
  const trip = await prisma.trip.findUnique({
    where: { id },
  });

  // 2. If someone types a random ID in the URL, show a 404 page
  if (!trip) {
    return notFound();
  }

  // 3. Extract the JSON itinerary generated by OpenAI
  const itineraryData: any = trip.itinerary;

  return (
    <main className="min-h-screen bg-stone-50 py-16 px-6">
      <div className="max-w-3xl mx-auto">
        
        {/* Header Section with a fade-in-down animation */}
        <div className="text-center mb-16 animate-in slide-in-from-top-8 fade-in duration-700">
          <Badge className="bg-stone-200 text-stone-800 hover:bg-stone-300 mb-6 px-4 py-1.5 text-sm rounded-full tracking-wide">
            {trip.duration} Days • {trip.members} Travelers • {trip.budget}
          </Badge>
          <h1 className="text-5xl md:text-6xl font-serif text-stone-900 mb-6 leading-tight">
            Your {trip.destination} Itinerary
          </h1>
          <p className="text-stone-500 text-lg md:text-xl">
            {itineraryData.trip_name || "A beautifully curated journey tailored just for you."}
          </p>
        </div>

        {/* The Timeline Map */}
        <div className="space-y-10">
          {itineraryData.itinerary?.map((day: any, index: number) => (
            <Card 
              key={index} 
              // Tailwind stagger animations based on the index to make them cascade in!
              className="border-none shadow-xl shadow-stone-200/50 overflow-hidden rounded-3xl animate-in slide-in-from-bottom-12 fade-in fill-mode-both"
              style={{ animationDuration: '800ms', animationDelay: `${index * 150}ms` }}
            >
              <CardHeader className="bg-stone-900 text-stone-50 py-5 px-8">
                <CardTitle className="text-2xl font-serif tracking-wide flex items-center justify-between">
                  <span>Day {day.day}</span>
                  <span className="text-sm font-sans font-normal text-stone-400">{day.theme}</span>
                </CardTitle>
              </CardHeader>
              
              <CardContent className="p-0 bg-white">
                {day.activities?.map((activity: any, actIndex: number) => (
                  <div 
                    key={actIndex} 
                    className="flex flex-col sm:flex-row gap-6 p-6 sm:p-8 border-b border-stone-100 last:border-0 hover:bg-stone-50/50 transition-colors"
                  >
                    {/* Time Column */}
                    <div className="sm:w-32 shrink-0 flex items-start gap-2 text-stone-500 font-medium">
                      <Clock size={18} className="mt-0.5" />
                      <span>{activity.time}</span>
                    </div>
                    
                    {/* Activity Details Column */}
                    <div className="flex-1">
                      <p className="text-stone-800 text-lg leading-relaxed mb-3">
                        {activity.description}
                      </p>
                      
                      <div className="flex flex-wrap gap-4 mt-4">
                        <span className="inline-flex items-center gap-1.5 text-sm text-stone-500 bg-stone-100 px-3 py-1 rounded-full">
                          <MapPin size={14} /> 
                          {activity.location}
                        </span>
                        <span className="inline-flex items-center gap-1.5 text-sm text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full font-medium">
                          <IndianRupee size={14} /> 
                          {activity.est_cost_in_inr}
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          ))}
        </div>

      </div>
    </main>
  );
}



  
  

  
